name: detached
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run with manual start'
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
          detached: true
