name: on failure
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        with:
          limit-access-to-actor: true
      - run: | 
          touch i-touched-it.txt
          sleep 30 && true
      - run: 'false'
