name: basic workflow dispatch example
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run with manual workflow dispatch'
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          ls -l >before-tmate.txt
  
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
      - run: |
          ls -l >after-tmate.txt
